# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qMsFWYGK9miOwchrCh8DvNW75K2_Q_vN
"""

#Import library pandas
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle

df = pd.read_csv("/content/pizza_v1.csv", sep=";")
df

# Ubah tipe data float menjadi integer u/ 1 kolom
df['diameter']=df['diameter'].astype(int)
df.info()

from sklearn.preprocessing import LabelEncoder
df[['size','extra_sauce','extra_cheese']]=df[['size','extra_sauce','extra_cheese']].apply(LabelEncoder().fit_transform)
df

df.drop(['company','topping','variant'],axis=1,inplace=True)
df

X = df.iloc[:,1:5]
X

y = df.iloc[:, 0]
y

#Splitting Training and Test Set
#Since we have a very small dataset, we will train our model with all availabe data.

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

#Fitting model with trainig data
regressor.fit(X.values, y)

import warnings

def fxn():
    warnings.warn("deprecated", DeprecationWarning)

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    fxn()

# Saving model to disk
pickle.dump(regressor, open('model.pkl','wb'))

# Loading model to compare the results
model = pickle.load(open('model.pkl','rb'))
print(model.predict([[14, 4, 0,1]]))

# Loading model to compare the results
model = pickle.load(open('model.pkl','rb'))
print(model.predict([[14, 4, 0,1]]))