# -*- coding: utf-8 -*-
"""request.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GfJKd2iEXg1ufP-NralRbRz3_-yrWy17
"""

import requests

url = 'http://localhost:5000/predict_api'
r = requests.post(url,json={'diameter':14, 'size':4, 'extra_sauce':0, 'extra_cheese': 1})

print(r.json())